### ISSUE TITLE
Use project ID instead of slug for URL

### ISSUE THREAD

**Issue by Zechiax** [Ricky12Awesome/packwiz-modlist#1]
When using the `{URL}` placeholder the generated URL is created from the slug of the project, which I think would be better if the project ID is used, because the slug can be changed.

Or it could be added as an another option, because when the slug is changed, the link will be unusable.

*By the way, thank You for this project! It helped me to save a lot of time ^^*

**Comment by Ricky12Awesome** [comment]
This would only effect modrinth projects, curseforge doesn't seem to accept using ids, but I made the change anyway in `v1.3.0`

**Comment by Zechiax** [comment]
I see, my bad, I was looking only at Modrinth and thought CurseForge is doing the same thing without checking. Looks like CurseForge is redirecting to the new URL after changing the slug, which is not the case on Modrinth

Thank you very much for blazingly fast response!
